/* @(#)AnimationSample.java

Copyright (c) 2009-2010 The authors and contributors of JHotDraw.

You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.samples.mini;
/**
 * AnimationSample displays a rotating ellipse figure.
 */
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
public class AnimationSample extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form AnimationSample
     */
    public AnimationSample() {
        initComponents();
        org.jhotdraw.draw.DefaultDrawingView view = new org.jhotdraw.draw.DefaultDrawingView();
        view.setDrawingDoubleBuffered(false);
        add(view);
        setSize(400, 400);
        org.jhotdraw.draw.Drawing d = new org.jhotdraw.draw.DefaultDrawing();
        d.attr().set(org.jhotdraw.draw.AttributeKeys.CANVAS_FILL_COLOR, new java.awt.Color(0x76a9d2));
        final org.jhotdraw.draw.figure.EllipseFigure ellipse = new org.jhotdraw.draw.figure.EllipseFigure(160, 160, 80, 80);
        ellipse.attr().set(org.jhotdraw.draw.AttributeKeys.STROKE_WIDTH, 7.0);
        d.add(ellipse);
        view.setDrawing(d);
        javax.swing.Timer t = new javax.swing.Timer(10, new java.awt.event.ActionListener() {
            @java.lang.Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                double alpha = ((2.0 * java.lang.Math.PI) * (java.lang.System.currentTimeMillis() % 1000)) / 1000.0;
                ellipse.willChange();
                ellipse.setBounds(new java.awt.geom.Rectangle2D.Double(160 + (java.lang.Math.sin(alpha) * 100), 160 + (java.lang.Math.cos(alpha) * 100), 80, 80));
                ellipse.changed();
            }
        });
        t.setRepeats(true);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @java.lang.SuppressWarnings("unchecked")
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     *
     * @param args
     * 		the command line arguments
     */
    public static void main(java.lang.String[] args) {
        java.lang.System.setProperty("apple.awt.graphics.UseQuartz", "false");
        java.awt.EventQueue.invokeLater(new java.lang.Runnable() {
            @java.lang.Override
            public void run() {
                new org.jhotdraw.samples.mini.AnimationSample().setVisible(true);
            }
        });
    }
}