/* @(#)SVGDrawingPanelSample.java

Copyright (c) 2009-2010 The authors and contributors of JHotDraw.

You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.samples.mini;
/**
 * Example showing how to embed the {@link org.jhotdraw.samples.svg.SVGDrawingPanel} into an
 * application that does not make use of the JHotDraw application framework.
 *
 * <p>In this case, the application consists of a JFrame with a File menu.
 */
// End of variables declaration//GEN-END:variables
public class SVGDrawingPanelSample extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /**
     * Holds the file chooser for opening a file.
     */
    private javax.swing.JFileChooser openChooser;

    /**
     * Holds the file chooser for saving a file.
     */
    private javax.swing.JFileChooser saveChooser;

    /**
     * Maps file filters to input formats, so that we can determine the input format that the user
     * selected for opening a drawing.
     */
    private java.util.HashMap<javax.swing.filechooser.FileFilter, org.jhotdraw.draw.io.InputFormat> fileFilterInputFormatMap;

    /**
     * Maps file filters to output formats, so that we can determine the output format that the user
     * selected for opening a drawing.
     */
    private java.util.HashMap<javax.swing.filechooser.FileFilter, org.jhotdraw.draw.io.OutputFormat> fileFilterOutputFormatMap;

    /**
     * Holds the currently opened file.
     */
    private java.io.File file;

    /**
     * Creates new form SVGDrawingPanelSample
     */
    public SVGDrawingPanelSample() {
        initComponents();
        setSize(new java.awt.Dimension(600, 400));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @java.lang.SuppressWarnings("unchecked")
    private void initComponents() {
        svgPanel = new org.jhotdraw.samples.svg.SVGDrawingPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        org.jhotdraw.samples.mini.SVGDrawingPanelSample.FormListener formListener = new org.jhotdraw.samples.mini.SVGDrawingPanelSample.FormListener();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(svgPanel, java.awt.BorderLayout.CENTER);
        fileMenu.setText("File");
        openMenuItem.setText("Open...");
        openMenuItem.addActionListener(formListener);
        fileMenu.add(openMenuItem);
        saveAsMenuItem.setText("Save As...");
        saveAsMenuItem.addActionListener(formListener);
        fileMenu.add(saveAsMenuItem);
        menuBar.add(fileMenu);
        setJMenuBar(menuBar);
        pack();
    }

    // Code for dispatching events from components to event handlers.
    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {
        }

        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == openMenuItem) {
                SVGDrawingPanelSample.this.open(evt);
            } else if (evt.getSource() == saveAsMenuItem) {
                SVGDrawingPanelSample.this.saveAs(evt);
            }
        }
    }

    /**
     * Opens a drawing from a file.
     */
    private void open(java.awt.event.ActionEvent evt) {
        // GEN-FIRST:event_open
        javax.swing.JFileChooser fc = getOpenChooser();
        if (file != null) {
            fc.setSelectedFile(file);
        }
        if (fc.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            svgPanel.setEnabled(false);
            final java.io.File selectedFile = fc.getSelectedFile();
            final org.jhotdraw.draw.io.InputFormat selectedFormat = fileFilterInputFormatMap.get(fc.getFileFilter());
            new javax.swing.SwingWorker() {
                @java.lang.Override
                protected java.lang.Object doInBackground() throws java.lang.Exception {
                    svgPanel.read(selectedFile.toURI(), selectedFormat);
                    return null;
                }

                @java.lang.Override
                protected void done() {
                    try {
                        get();
                        file = selectedFile;
                        setTitle(file.getName());
                    } catch (java.lang.InterruptedException | java.util.concurrent.ExecutionException ex) {
                        java.util.logging.Logger.getLogger(org.jhotdraw.samples.mini.SVGDrawingPanelSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        failed(ex);
                    }
                    finished();
                }

                protected void failed(java.lang.Throwable error) {
                    error.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(SVGDrawingPanelSample.this, (("<html><b>Couldn't open file \"" + selectedFile.getName()) + "\"<br>") + error.toString(), "Open File", javax.swing.JOptionPane.ERROR_MESSAGE);
                }

                protected void finished() {
                    svgPanel.setEnabled(true);
                }
            }.execute();
        }
    }// GEN-LAST:event_open


    /**
     * Saves a drawing to a file.
     */
    private void saveAs(java.awt.event.ActionEvent evt) {
        // GEN-FIRST:event_saveAs
        javax.swing.JFileChooser fc = getSaveChooser();
        if (file != null) {
            fc.setSelectedFile(file);
        }
        if (fc.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            svgPanel.setEnabled(false);
            final java.io.File selectedFile = fc.getSelectedFile();
            final org.jhotdraw.draw.io.OutputFormat selectedFormat = fileFilterOutputFormatMap.get(fc.getFileFilter());
            new javax.swing.SwingWorker() {
                @java.lang.Override
                protected java.lang.Object doInBackground() throws java.lang.Exception {
                    svgPanel.write(selectedFile.toURI(), selectedFormat);
                    return null;
                }

                @java.lang.Override
                protected void done() {
                    try {
                        get();
                        file = selectedFile;
                        setTitle(file.getName());
                    } catch (java.lang.InterruptedException | java.util.concurrent.ExecutionException ex) {
                        java.util.logging.Logger.getLogger(org.jhotdraw.samples.mini.SVGDrawingPanelSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        failed(ex);
                    }
                    finished();
                }

                protected void failed(java.lang.Throwable error) {
                    error.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(SVGDrawingPanelSample.this, (("<html><b>Couldn't save to file \"" + selectedFile.getName()) + "\"<br>") + error.toString(), "Save As File", javax.swing.JOptionPane.ERROR_MESSAGE);
                }

                protected void finished() {
                    svgPanel.setEnabled(true);
                }
            }.execute();
        }
    }// GEN-LAST:event_saveAs


    /**
     * Lazily creates a JFileChooser and returns it.
     */
    private javax.swing.JFileChooser getOpenChooser() {
        if (openChooser == null) {
            openChooser = new javax.swing.JFileChooser();
            org.jhotdraw.draw.Drawing d = svgPanel.getDrawing();
            fileFilterInputFormatMap = new java.util.HashMap<javax.swing.filechooser.FileFilter, org.jhotdraw.draw.io.InputFormat>();
            javax.swing.filechooser.FileFilter firstFF = null;
            for (org.jhotdraw.draw.io.InputFormat format : d.getInputFormats()) {
                javax.swing.filechooser.FileFilter ff = format.getFileFilter();
                if (firstFF == null) {
                    firstFF = ff;
                }
                fileFilterInputFormatMap.put(ff, format);
                openChooser.addChoosableFileFilter(ff);
            }
            openChooser.setFileFilter(firstFF);
            openChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                @java.lang.Override
                public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    if ("fileFilterChanged".equals(evt.getPropertyName())) {
                        org.jhotdraw.draw.io.InputFormat inputFormat = fileFilterInputFormatMap.get(evt.getNewValue());
                        openChooser.setAccessory(null);
                    }
                }
            });
        }
        return openChooser;
    }

    /**
     * Lazily creates a JFileChooser and returns it.
     */
    private javax.swing.JFileChooser getSaveChooser() {
        if (saveChooser == null) {
            saveChooser = new javax.swing.JFileChooser();
            org.jhotdraw.draw.Drawing d = svgPanel.getDrawing();
            fileFilterOutputFormatMap = new java.util.HashMap<javax.swing.filechooser.FileFilter, org.jhotdraw.draw.io.OutputFormat>();
            javax.swing.filechooser.FileFilter firstFF = null;
            for (org.jhotdraw.draw.io.OutputFormat format : d.getOutputFormats()) {
                javax.swing.filechooser.FileFilter ff = format.getFileFilter();
                if (firstFF == null) {
                    firstFF = ff;
                }
                fileFilterOutputFormatMap.put(ff, format);
                saveChooser.addChoosableFileFilter(ff);
            }
            saveChooser.setFileFilter(firstFF);
            saveChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                @java.lang.Override
                public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    if ("fileFilterChanged".equals(evt.getPropertyName())) {
                        org.jhotdraw.draw.io.OutputFormat outputFormat = fileFilterOutputFormatMap.get(evt.getNewValue());
                        saveChooser.setAccessory(null);
                    }
                }
            });
        }
        return saveChooser;
    }

    /**
     *
     * @param args
     * 		the command line arguments
     */
    public static void main(java.lang.String[] args) {
        java.awt.EventQueue.invokeLater(new java.lang.Runnable() {
            @java.lang.Override
            public void run() {
                new org.jhotdraw.samples.mini.SVGDrawingPanelSample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;

    private javax.swing.JMenuBar menuBar;

    private javax.swing.JMenuItem openMenuItem;

    private javax.swing.JMenuItem saveAsMenuItem;

    private org.jhotdraw.samples.svg.SVGDrawingPanel svgPanel;
}