/* @(#)JAttributeTextField.java

Copyright (c) 2009-2010 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.draw.gui;
/**
 * An entry field that can be used to edit an attribute of a {@code Figure}.
 */
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
public class JAttributeTextField<T> extends org.jhotdraw.gui.JLifeFormattedTextField implements org.jhotdraw.api.gui.AttributeEditor<T> {
    private static final long serialVersionUID = 1L;

    /**
     * This variable is set to true, when the figures, which are currently being edited by this field,
     * have multiple values.
     */
    private boolean isMultipleValues;

    /**
     * Creates new instance.
     */
    public JAttributeTextField() {
    }

    @java.lang.Override
    protected void paintComponent(java.awt.Graphics g) {
        if ((!isFocusOwner()) && isMultipleValues) {
            org.jhotdraw.util.ResourceBundleUtil labels = org.jhotdraw.util.ResourceBundleUtil.getBundle("org.jhotdraw.gui.Labels");
            java.awt.Color c = getForeground();
            setForeground(new java.awt.Color(0x0, true));
            super.paintComponent(g);
            java.awt.Insets insets = getInsets();
            java.awt.Insets margin = getMargin();
            java.awt.FontMetrics fm = g.getFontMetrics(getFont());
            g.setFont(getFont().deriveFont(java.awt.Font.ITALIC));
            setForeground(c);
            g.setColor(c);
            g.drawString(labels.getString("attribute.differentValues.text"), insets.left + margin.left, (insets.top + margin.top) + fm.getAscent());
        } else {
            super.paintComponent(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    @java.lang.Override
    public javax.swing.JComponent getComponent() {
        return this;
    }

    @java.lang.SuppressWarnings("unchecked")
    @java.lang.Override
    public T getAttributeValue() {
        return ((T) (getValue()));
    }

    @java.lang.Override
    public void setMultipleValues(boolean newValue) {
        isMultipleValues = newValue;
        repaint();
    }

    @java.lang.Override
    public boolean isMultipleValues() {
        return isMultipleValues;
    }

    @java.lang.Override
    public boolean getValueIsAdjusting() {
        return isFocusOwner();
    }

    @java.lang.Override
    public void setAttributeValue(T newValue) {
        setValue(newValue);
    }

    @java.lang.Override
    protected void firePropertyChange(java.lang.String propertyName, java.lang.Object oldValue, java.lang.Object newValue) {
        super.firePropertyChange(propertyName, oldValue, newValue);
        if ("value".equals(propertyName)) {
            super.firePropertyChange(org.jhotdraw.api.gui.AttributeEditor.ATTRIBUTE_VALUE_PROPERTY, oldValue, newValue);
        }
    }
}