/* @(#)JAttributeSlider.java

Copyright (c) 2007 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.draw.gui;
/**
 * A JSlider that can be used to edit a double attribute of a Figure.
 */
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
public class JAttributeSlider extends javax.swing.JSlider implements org.jhotdraw.api.gui.AttributeEditor<java.lang.Double> {
    private static final long serialVersionUID = 1L;

    private boolean isMultipleValues;

    private java.lang.Double attributeValue;

    private double scaleFactor = 1.0;

    /**
     * Creates new instance.
     */
    public JAttributeSlider() {
        this(javax.swing.JSlider.VERTICAL, 0, 100, 50);
    }

    public JAttributeSlider(int orientation, int min, int max, int value) {
        super(orientation, min, max, value);
    }

    @java.lang.Override
    public javax.swing.JComponent getComponent() {
        return this;
    }

    @java.lang.Override
    public void setAttributeValue(java.lang.Double newValue) {
        attributeValue = newValue;
        setValue(attributeValue == null ? 0 : ((int) (attributeValue * scaleFactor)));
    }

    @java.lang.Override
    public java.lang.Double getAttributeValue() {
        return attributeValue;
    }

    public void setScaleFactor(double newValue) {
        scaleFactor = newValue;
    }

    public double getScaleFactor() {
        return scaleFactor;
    }

    @java.lang.Override
    public void setMultipleValues(boolean newValue) {
        boolean oldValue = isMultipleValues;
        isMultipleValues = newValue;
        firePropertyChange(org.jhotdraw.api.gui.AttributeEditor.MULTIPLE_VALUES_PROPERTY, oldValue, newValue);
    }

    @java.lang.Override
    public boolean isMultipleValues() {
        throw new java.lang.UnsupportedOperationException("Not supported yet.");
    }

    @java.lang.Override
    protected void fireStateChanged() {
        super.fireStateChanged();
        java.lang.Double oldValue = attributeValue;
        attributeValue = getValue() / scaleFactor;
        firePropertyChange(org.jhotdraw.api.gui.AttributeEditor.ATTRIBUTE_VALUE_PROPERTY, oldValue, attributeValue);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents

}