/* @(#)CIEXYChromaticityDiagram.java

Copyright (c) 2010 The authors and contributors of JHotDraw.

You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.samples.color;
/**
 * CIEXYChromaticityDiagram.
 */
public class CIEXYChromaticityDiagram extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    private org.jhotdraw.color.CIEXYChromaticityDiagramImageProducer imageProducer;

    private java.awt.Image image;

    /**
     * Creates new form CIEXYChromaticityDiagram
     */
    public CIEXYChromaticityDiagram() {
        initComponents();
    }

    @java.lang.Override
    public void paintComponent(java.awt.Graphics gr) {
        java.awt.Graphics2D g = ((java.awt.Graphics2D) (gr));
        int side = java.lang.Math.min(this.getWidth(), this.getHeight());
        if ((imageProducer == null) || (imageProducer.getWidth() != side)) {
            if (image != null) {
                image.flush();
            }
            imageProducer = new org.jhotdraw.color.CIEXYChromaticityDiagramImageProducer(side, side);
            imageProducer.generateImage();
            image = getToolkit().createImage(imageProducer);
        }
        g.drawImage(image, 0, 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @java.lang.SuppressWarnings("unchecked")
    private void initComponents() {
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, java.lang.Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300, java.lang.Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public static void main(java.lang.String[] args) {
        javax.swing.SwingUtilities.invokeLater(new java.lang.Runnable() {
            @java.lang.Override
            public void run() {
                javax.swing.JFrame f = new javax.swing.JFrame("CIE xy Chromaticity Diagram");
                f.add(new org.jhotdraw.samples.color.CIEXYChromaticityDiagram());
                f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                f.setSize(400, 400);
                f.setVisible(true);
            }
        });
    }
}