/* @(#)FontChooserMain.java

Copyright (c) 2008 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.samples.font;
/**
 * FontChooserMain.
 */
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
public class FontChooserMain extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form FontChooserMain
     */
    public FontChooserMain() {
        initComponents();
        add(new org.jhotdraw.gui.JFontChooser());
    }

    public static void main(java.lang.String[] args) {
        javax.swing.SwingUtilities.invokeLater(new java.lang.Runnable() {
            @java.lang.Override
            public void run() {
                try {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                } catch (java.lang.Throwable t) {
                    // allow empty
                }
                javax.swing.JFrame f = new javax.swing.JFrame("FontChooser");
                f.add(new org.jhotdraw.samples.font.FontChooserMain());
                f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                f.pack();
                f.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @java.lang.SuppressWarnings("unchecked")
    private void initComponents() {
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

}