/**
 *
 * @(#)JDisclosureToolBar.java <p>Copyright (c) 2008 The authors and contributors of JHotDraw. You may not use, copy or modify
this file, except in compliance with the accompanying license terms.
 */
package org.jhotdraw.gui;
/**
 * A ToolBar with disclosure functionality.
 */
/**
 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
 * modify this code. The content of this method is always regenerated by the Form Editor. / //
 * <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents private
 * void initComponents() { }// </editor-fold>//GEN-END:initComponents
 */
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
public class JDisclosureToolBar extends javax.swing.JToolBar {
    private static final long serialVersionUID = 1L;

    private javax.swing.JButton disclosureButton;

    public static final java.lang.String DISCLOSURE_STATE_PROPERTY = "disclosureState";

    public static final java.lang.String DISCLOSURE_STATE_COUNT_PROPERTY = "disclosureStateCount";

    /**
     * Creates new form.
     */
    public JDisclosureToolBar() {
        setUI(org.jhotdraw.gui.plaf.palette.PaletteToolBarUI.createUI(this));
        initComponents();
    }

    private void initComponents() {
        java.awt.GridBagConstraints gbc;
        javax.swing.AbstractButton btn;
        setLayout(new java.awt.GridBagLayout());
        gbc = new java.awt.GridBagConstraints();
        if (disclosureButton == null) {
            btn = new javax.swing.JButton();
            btn.setUI(((org.jhotdraw.gui.plaf.palette.PaletteButtonUI) (org.jhotdraw.gui.plaf.palette.PaletteButtonUI.createUI(btn))));
            btn.setBorderPainted(false);
            btn.setIcon(new org.jhotdraw.gui.DisclosureIcon());
            btn.setOpaque(false);
            disclosureButton = ((javax.swing.JButton) (btn));
            disclosureButton.putClientProperty(org.jhotdraw.gui.DisclosureIcon.CURRENT_STATE_PROPERTY, 1);
            disclosureButton.putClientProperty(org.jhotdraw.gui.DisclosureIcon.STATE_COUNT_PROPERTY, 2);
            disclosureButton.addActionListener(new java.awt.event.ActionListener() {
                @java.lang.Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    int newState = (((java.lang.Integer) (disclosureButton.getClientProperty(org.jhotdraw.gui.DisclosureIcon.CURRENT_STATE_PROPERTY))) + 1) % ((java.lang.Integer) (disclosureButton.getClientProperty(org.jhotdraw.gui.DisclosureIcon.STATE_COUNT_PROPERTY)));
                    setDisclosureState(newState);
                }
            });
        } else {
            btn = disclosureButton;
        }
        gbc.gridx = 0;
        gbc.insets = new java.awt.Insets(0, 1, 0, 1);
        gbc.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gbc.fill = java.awt.GridBagConstraints.NONE;
        gbc.weighty = 1.0;
        gbc.weightx = 1.0;
        add(btn, gbc);
        putClientProperty(org.jhotdraw.gui.plaf.palette.PaletteToolBarUI.TOOLBAR_INSETS_OVERRIDE_PROPERTY, new java.awt.Insets(0, 0, 0, 0));
        putClientProperty(org.jhotdraw.gui.plaf.palette.PaletteToolBarUI.TOOLBAR_ICON_PROPERTY, new org.jhotdraw.gui.EmptyIcon(10, 8));
    }

    public void setDisclosureStateCount(int newValue) {
        int oldValue = getDisclosureStateCount();
        disclosureButton.putClientProperty(org.jhotdraw.gui.DisclosureIcon.STATE_COUNT_PROPERTY, newValue);
        firePropertyChange(org.jhotdraw.gui.JDisclosureToolBar.DISCLOSURE_STATE_COUNT_PROPERTY, oldValue, newValue);
    }

    public void setDisclosureState(int newValue) {
        int oldValue = getDisclosureState();
        disclosureButton.putClientProperty(org.jhotdraw.gui.DisclosureIcon.CURRENT_STATE_PROPERTY, newValue);
        removeAll();
        javax.swing.JComponent c = getDisclosedComponent(newValue);
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        if (c != null) {
            gbc = new java.awt.GridBagConstraints();
            gbc.gridx = 1;
            gbc.weightx = 1.0;
            gbc.weighty = 1.0;
            gbc.fill = java.awt.GridBagConstraints.BOTH;
            gbc.anchor = java.awt.GridBagConstraints.WEST;
            add(c, gbc);
            gbc = new java.awt.GridBagConstraints();
            gbc.gridx = 0;
            gbc.weightx = 0.0;
            gbc.insets = new java.awt.Insets(0, 1, 0, 1);
            gbc.weighty = 1.0;
            gbc.fill = java.awt.GridBagConstraints.NONE;
            gbc.anchor = java.awt.GridBagConstraints.SOUTHWEST;
            add(disclosureButton, gbc);
        } else {
            gbc = new java.awt.GridBagConstraints();
            gbc.gridx = 1;
            gbc.weightx = 1.0;
            gbc.weighty = 1.0;
            gbc.fill = java.awt.GridBagConstraints.NONE;
            gbc.anchor = java.awt.GridBagConstraints.SOUTHWEST;
            gbc.insets = new java.awt.Insets(0, 1, 0, 1);
            add(disclosureButton, gbc);
        }
        invalidate();
        java.awt.Container parent = getParent();
        while ((parent.getParent() != null) && (!parent.getParent().isValid())) {
            parent = parent.getParent();
        } 
        parent.validate();
        repaint();
        firePropertyChange(org.jhotdraw.gui.JDisclosureToolBar.DISCLOSURE_STATE_PROPERTY, oldValue, newValue);
    }

    public int getDisclosureStateCount() {
        java.lang.Integer value = ((java.lang.Integer) (disclosureButton.getClientProperty(org.jhotdraw.gui.DisclosureIcon.STATE_COUNT_PROPERTY)));
        return value == null ? 2 : value;
    }

    public int getDisclosureState() {
        java.lang.Integer value = ((java.lang.Integer) (disclosureButton.getClientProperty(org.jhotdraw.gui.DisclosureIcon.CURRENT_STATE_PROPERTY)));
        return value == null ? 1 : value;
    }

    protected javax.swing.JComponent getDisclosedComponent(int state) {
        return new javax.swing.JLabel(java.lang.Integer.toString(state));
    }
}