/* @(#)JFontChooser.java

Copyright (c) 2008 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.gui;
/**
 * Font chooser dialog.
 */
/**
 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
 * modify this code. The content of this method is always regenerated by the Form Editor. / //
 * <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents private
 * void initComponents() { }// </editor-fold>//GEN-END:initComponents
 */
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
public class JFontChooser extends javax.swing.JComponent {
    private static final long serialVersionUID = 1L;

    /**
     *
     * @see #getUIClassID
     * @see #readObject
     */
    private static final java.lang.String UI_CLASS_ID = "FontChooserUI";

    /**
     * Identifies the "selectedFont" property.
     */
    public static final java.lang.String SELECTED_FONT_PROPERTY = "selectedFont";

    /**
     * Identifies the "selectionPath" property.
     */
    public static final java.lang.String SELECTION_PATH_PROPERTY = "selectionPath";

    /**
     * Instruction to cancel the current selection.
     */
    public static final java.lang.String CANCEL_SELECTION = "CancelSelection";

    /**
     * Instruction to approve the current selection (same as pressing yes or ok).
     */
    public static final java.lang.String APPROVE_SELECTION = "ApproveSelection";

    /**
     * Identifies the "model" property.
     */
    public static final java.lang.String MODEL_PROPERTY = "model";

    /**
     * Holds the selected path of the JFontChooser.
     */
    private javax.swing.tree.TreePath selectionPath;

    /**
     * Holds the selected font of the JFontChooser.
     */
    private java.awt.Font selectedFont;

    /**
     * Holds the model of the JFontChooser.
     */
    private org.jhotdraw.gui.fontchooser.FontChooserModel model;

    // ********************************
    // ***** Dialog Return Values *****
    // ********************************
    /**
     * Return value if cancel is chosen.
     */
    public static final int CANCEL_OPTION = 1;

    /**
     * Return value if approve (yes, ok) is chosen.
     */
    public static final int APPROVE_OPTION = 0;

    /**
     * Return value if an error occured.
     */
    public static final int ERROR_OPTION = -1;

    private int returnValue = org.jhotdraw.gui.JFontChooser.ERROR_OPTION;

    // DIALOG
    private javax.swing.JDialog dialog = null;

    /**
     * This future is used to load fonts lazily
     */
    private static java.util.concurrent.FutureTask<java.awt.Font[]> future;

    private javax.swing.event.TreeModelListener modelHandler = new javax.swing.event.TreeModelListener() {
        @java.lang.Override
        public void treeNodesChanged(javax.swing.event.TreeModelEvent e) {
            updateSelectionPath(getSelectedFont());
        }

        @java.lang.Override
        public void treeNodesInserted(javax.swing.event.TreeModelEvent e) {
            updateSelectionPath(getSelectedFont());
        }

        @java.lang.Override
        public void treeNodesRemoved(javax.swing.event.TreeModelEvent e) {
            updateSelectionPath(getSelectedFont());
        }

        @java.lang.Override
        public void treeStructureChanged(javax.swing.event.TreeModelEvent e) {
            updateSelectionPath(getSelectedFont());
        }
    };

    /**
     * Creates new form JFontChooser
     */
    public JFontChooser() {
        org.jhotdraw.gui.JFontChooser.loadAllFonts();
        model = new org.jhotdraw.gui.fontchooser.DefaultFontChooserModel.UIResource();
        model.addTreeModelListener(modelHandler);
        updateUI();
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            @java.lang.Override
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                if ("ancestor".equals(evt.getPropertyName()) && (evt.getNewValue() != null)) {
                    try {
                        ((org.jhotdraw.gui.fontchooser.DefaultFontChooserModel) (model)).setFonts(org.jhotdraw.gui.JFontChooser.getAllFonts());
                    } catch (java.lang.Exception ex) {
                        ex.printStackTrace();
                    }
                    JFontChooser.this.removePropertyChangeListener(this);
                }
            }
        });
    }

    /**
     * Resets the UI property with a value from the current look and feel.
     *
     * @see JComponent#updateUI
     */
    @java.lang.Override
    public void updateUI() {
        // Try to get a browser UI from the UIManager.
        // Fall back to BasicBrowserUI, if none is available.
        if (javax.swing.UIManager.get(getUIClassID()) != null) {
            setUI(((org.jhotdraw.gui.plaf.FontChooserUI) (javax.swing.UIManager.getUI(this))));
        } else {
            setUI(org.jhotdraw.gui.plaf.palette.PaletteFontChooserUI.createUI(this));
        }
    }

    /**
     * Returns the look and feel (L&amp;F) object that renders this component.
     *
     * @return the PanelUI object that renders this component
     * @since 1.4
     */
    public org.jhotdraw.gui.plaf.FontChooserUI getUI() {
        return ((org.jhotdraw.gui.plaf.FontChooserUI) (ui));
    }

    /**
     * Sets the look and feel (L&amp;F) object that renders this component.
     *
     * @param ui
     * 		the PanelUI L&amp;F object
     * @see UIDefaults#getUI
     */
    public void setUI(org.jhotdraw.gui.plaf.FontChooserUI ui) {
        super.setUI(ui);
    }

    /**
     * Returns a string that specifies the name of the L&amp;F class that renders this component.
     *
     * @return "FontChooserUI"
     * @see JComponent#getUIClassID
     * @see UIDefaults#getUI
     */
    @java.lang.Override
    public java.lang.String getUIClassID() {
        return org.jhotdraw.gui.JFontChooser.UI_CLASS_ID;
    }

    /**
     * Called by the UI when the user hits the Approve button (labeled "Open" or "Save", by default).
     * This can also be called by the programmer. This method causes an action event to fire with the
     * command string equal to <code>APPROVE_SELECTION</code>.
     *
     * @see #APPROVE_SELECTION
     */
    public void approveSelection() {
        returnValue = org.jhotdraw.gui.JFontChooser.APPROVE_OPTION;
        if (dialog != null) {
            dialog.setVisible(false);
        }
        fireActionPerformed(org.jhotdraw.gui.JFontChooser.APPROVE_SELECTION);
    }

    /**
     * Called by the UI when the user chooses the Cancel button. This can also be called by the
     * programmer. This method causes an action event to fire with the command string equal to <code>
     * CANCEL_SELECTION</code>.
     *
     * @see #CANCEL_SELECTION
     */
    public void cancelSelection() {
        returnValue = org.jhotdraw.gui.JFontChooser.CANCEL_OPTION;
        if (dialog != null) {
            dialog.setVisible(false);
        }
        fireActionPerformed(org.jhotdraw.gui.JFontChooser.CANCEL_SELECTION);
    }

    /**
     * Adds an <code>ActionListener</code> to the font chooser.
     *
     * @param l
     * 		the listener to be added
     * @see #approveSelection
     * @see #cancelSelection
     */
    public void addActionListener(java.awt.event.ActionListener l) {
        listenerList.add(java.awt.event.ActionListener.class, l);
    }

    /**
     * Removes an <code>ActionListener</code> from the font chooser.
     *
     * @param l
     * 		the listener to be removed
     * @see #addActionListener
     */
    public void removeActionListener(java.awt.event.ActionListener l) {
        listenerList.remove(java.awt.event.ActionListener.class, l);
    }

    /**
     * Notifies all listeners that have registered interest for notification on this event type. The
     * event instance is lazily created using the <code>command</code> parameter.
     */
    protected void fireActionPerformed(java.lang.String command) {
        // Guaranteed to return a non-null array
        java.lang.Object[] listeners = listenerList.getListenerList();
        long mostRecentEventTime = java.awt.EventQueue.getMostRecentEventTime();
        int modifiers = 0;
        java.awt.AWTEvent currentEvent = java.awt.EventQueue.getCurrentEvent();
        if (currentEvent instanceof java.awt.event.InputEvent) {
            modifiers = ((java.awt.event.InputEvent) (currentEvent)).getModifiers();
        } else if (currentEvent instanceof java.awt.event.ActionEvent) {
            modifiers = ((java.awt.event.ActionEvent) (currentEvent)).getModifiers();
        }
        java.awt.event.ActionEvent e = null;
        // Process the listeners last to first, notifying
        // those that are interested in this event
        for (int i = listeners.length - 2; i >= 0; i -= 2) {
            if (listeners[i] == java.awt.event.ActionListener.class) {
                // Lazily create the event:
                if (e == null) {
                    e = new java.awt.event.ActionEvent(this, java.awt.event.ActionEvent.ACTION_PERFORMED, command, mostRecentEventTime, modifiers);
                }
                ((java.awt.event.ActionListener) (listeners[i + 1])).actionPerformed(e);
            }
        }
    }

    /**
     * Gets the selected Font. This is a bound property.
     *
     * @return The selected font, or null, if no font is selected.
     */
    public javax.swing.tree.TreePath getSelectionPath() {
        return selectionPath;
    }

    /**
     * Sets the selected Font. This is a bound property.
     *
     * <p>Changing the selection path, causes a change of the selected font, if the selected font is
     * not the last path segment of the selection path.
     *
     * @param newValue
     * 		The new selected font, or null if no font is to be selected..
     */
    public void setSelectionPath(javax.swing.tree.TreePath newValue) {
        javax.swing.tree.TreePath oldValue = selectionPath;
        this.selectionPath = newValue;
        firePropertyChange(org.jhotdraw.gui.JFontChooser.SELECTION_PATH_PROPERTY, oldValue, newValue);
        if ((selectionPath != null) && (selectionPath.getPathCount() == 4)) {
            setSelectedFont(((org.jhotdraw.gui.fontchooser.FontFaceNode) (selectionPath.getLastPathComponent())).getFont());
        }
    }

    /**
     * Starts loading all fonts from the local graphics environment using a worker thread.
     */
    public static synchronized void loadAllFonts() {
        if (org.jhotdraw.gui.JFontChooser.future == null) {
            org.jhotdraw.gui.JFontChooser.future = new java.util.concurrent.FutureTask<>(new java.util.concurrent.Callable<java.awt.Font[]>() {
                @java.lang.Override
                public java.awt.Font[] call() throws java.lang.Exception {
                    java.awt.Font[] fonts = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getAllFonts();
                    // get rid of bogus fonts
                    java.util.ArrayList<java.awt.Font> goodFonts = new java.util.ArrayList<>(fonts.length);
                    for (java.awt.Font f : fonts) {
                        // System.out.println("JFontChooser "+f.getFontName());
                        java.awt.Font decoded = java.awt.Font.decode(f.getFontName());
                        if (decoded.getFontName().equals(f.getFontName()) || decoded.getFontName().endsWith("-Derived")) {
                            goodFonts.add(f);
                        } else {
                            // System.out.println("JFontChooser ***bogus*** "+decoded.getFontName());
                        }
                    }
                    return goodFonts.toArray(new java.awt.Font[goodFonts.size()]);
                    // return fonts;
                }
            });
            new java.lang.Thread(org.jhotdraw.gui.JFontChooser.future).start();
        }
    }

    /**
     * Gets all fonts from the graphics environment. This may take a long time. It is recommended to
     * call loadAllFonts during the startup of an application. If you do this, you can retrieve the
     * fonts from this method from the AWT Event Dispatcher Thread.
     *
     * @return All fonts.
     */
    public static synchronized java.awt.Font[] getAllFonts() {
        org.jhotdraw.gui.JFontChooser.loadAllFonts();
        try {
            return org.jhotdraw.gui.JFontChooser.future.get().clone();
        } catch (java.lang.InterruptedException | java.util.concurrent.ExecutionException ex) {
            return new java.awt.Font[0];
        }
    }

    /**
     * Gets the selected Font. This is a bound property.
     *
     * @return The selected font, or null, if no font is selected.
     */
    public java.awt.Font getSelectedFont() {
        return selectedFont;
    }

    /**
     * Sets the selected Font.
     *
     * <p>Changing the selected font, causes a change of the selection path, if the selected font is
     * not the last path segment of the selection path.
     *
     * <p>This is a bound property.
     *
     * @param newValue
     * 		The new selected font, or null if no font is to be selected.
     */
    public void setSelectedFont(java.awt.Font newValue) {
        java.awt.Font oldValue = selectedFont;
        this.selectedFont = newValue;
        firePropertyChange(org.jhotdraw.gui.JFontChooser.SELECTED_FONT_PROPERTY, oldValue, newValue);
        updateSelectionPath(newValue);
    }

    /**
     * Updates the selection path to the selected font.
     *
     * <p>This method is invoked, when a font is selected, and when then structure of the model has
     * changed.
     *
     * @param newValue
     */
    protected void updateSelectionPath(java.awt.Font newValue) {
        if ((((newValue == null) || (selectionPath == null)) || (selectionPath.getPathCount() != 4)) || (!((org.jhotdraw.gui.fontchooser.FontFaceNode) (selectionPath.getLastPathComponent())).getFont().getFontName().equals(newValue.getFontName()))) {
            if (newValue == null) {
                setSelectionPath(null);
            } else {
                javax.swing.tree.TreePath path = selectionPath;
                org.jhotdraw.gui.fontchooser.FontCollectionNode oldCollection = ((path != null) && (path.getPathCount() > 1)) ? ((org.jhotdraw.gui.fontchooser.FontCollectionNode) (path.getPathComponent(1))) : null;
                org.jhotdraw.gui.fontchooser.FontFamilyNode oldFamily = ((path != null) && (path.getPathCount() > 2)) ? ((org.jhotdraw.gui.fontchooser.FontFamilyNode) (path.getPathComponent(2))) : null;
                org.jhotdraw.gui.fontchooser.FontFaceNode oldFace = ((path != null) && (path.getPathCount() > 3)) ? ((org.jhotdraw.gui.fontchooser.FontFaceNode) (path.getPathComponent(3))) : null;
                org.jhotdraw.gui.fontchooser.FontCollectionNode newCollection = oldCollection;
                org.jhotdraw.gui.fontchooser.FontFamilyNode newFamily = oldFamily;
                org.jhotdraw.gui.fontchooser.FontFaceNode newFace = null;
                // search in the current family
                if ((newFace == null) && (newFamily != null)) {
                    for (org.jhotdraw.gui.fontchooser.FontFaceNode face : newFamily.faces()) {
                        if (face.getFont().getFontName().equals(newValue.getFontName())) {
                            newFace = face;
                            break;
                        }
                    }
                }
                // search in the current collection
                if ((newFace == null) && (newCollection != null)) {
                    for (org.jhotdraw.gui.fontchooser.FontFamilyNode family : newCollection.families()) {
                        for (org.jhotdraw.gui.fontchooser.FontFaceNode face : family.faces()) {
                            if (face.getFont().getFontName().equals(newValue.getFontName())) {
                                newFamily = family;
                                newFace = face;
                                break;
                            }
                        }
                    }
                }
                // search in all collections
                if (newFace == null) {
                    javax.swing.tree.TreeNode root = ((javax.swing.tree.TreeNode) (getModel().getRoot()));
                    OuterLoop : for (int i = 0, n = root.getChildCount(); i < n; i++) {
                        org.jhotdraw.gui.fontchooser.FontCollectionNode collection = ((org.jhotdraw.gui.fontchooser.FontCollectionNode) (root.getChildAt(i)));
                        for (org.jhotdraw.gui.fontchooser.FontFamilyNode family : collection.families()) {
                            for (org.jhotdraw.gui.fontchooser.FontFaceNode face : family.faces()) {
                                if (face.getFont().getFontName().equals(newValue.getFontName())) {
                                    newCollection = collection;
                                    newFamily = family;
                                    newFace = face;
                                    break OuterLoop;
                                }
                            }
                        }
                    }
                }
                if (newFace != null) {
                    setSelectionPath(new javax.swing.tree.TreePath(new java.lang.Object[]{ getModel().getRoot(), newCollection, newFamily, newFace }));
                } else {
                    setSelectionPath(null);
                }
            }
        }
    }

    /**
     * Gets the selected Font. This is a bound property.
     *
     * @return The selected font, or null, if no font is selected.
     */
    public org.jhotdraw.gui.fontchooser.FontChooserModel getModel() {
        return model;
    }

    /**
     * Sets the selected Font. This is a bound property.
     *
     * @param newValue
     * 		The new selected font, or null if no font is to be selected..
     */
    public void setModel(org.jhotdraw.gui.fontchooser.FontChooserModel newValue) {
        org.jhotdraw.gui.fontchooser.FontChooserModel oldValue = model;
        if (oldValue != null) {
            oldValue.removeTreeModelListener(modelHandler);
        }
        this.model = newValue;
        if (newValue != null) {
            newValue.addTreeModelListener(modelHandler);
        }
        firePropertyChange(org.jhotdraw.gui.JFontChooser.MODEL_PROPERTY, oldValue, newValue);
        updateSelectionPath(selectedFont);
    }
}