/* @(#)JLifeFormattedTextArea.java

Copyright (c) 2009-2010 The authors and contributors of JHotDraw.

You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.gui;
/**
 * JLifeFormattedTextArea.
 */
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
public class JLifeFormattedTextArea extends javax.swing.JTextArea {
    private static final long serialVersionUID = 1L;

    /**
     * This adapter is used for adapting Formatters to the JTextArea.
     */
    private org.jhotdraw.gui.JLifeFormattedTextField formattedTextFieldAdapter;

    /**
     * Forwards property change events from the formattedTextFieldAdapter to listeners of this object.
     */
    private java.beans.PropertyChangeListener handler;

    /**
     * Creates new instance.
     */
    public JLifeFormattedTextArea() {
    }

    @java.lang.Override
    public void setDocument(javax.swing.text.Document newValue) {
        super.setDocument(newValue);
        // We must check for null here, because setDocument is called in the
        // super class constructor.
        if (formattedTextFieldAdapter == null) {
            formattedTextFieldAdapter = new org.jhotdraw.gui.JLifeFormattedTextField();
            handler = new java.beans.PropertyChangeListener() {
                @java.lang.Override
                public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    if ((evt.getSource() == formattedTextFieldAdapter) && "value".equals(evt.getPropertyName())) {
                        firePropertyChange(evt.getPropertyName(), evt.getOldValue(), evt.getNewValue());
                    }
                }
            };
            formattedTextFieldAdapter.addPropertyChangeListener(handler);
        }
        formattedTextFieldAdapter.setDocument(newValue);
    }

    public void setValue(java.lang.Object value) {
        formattedTextFieldAdapter.setValue(value);
    }

    public java.lang.Object getValue() {
        return formattedTextFieldAdapter.getValue();
    }

    public void setFormatterFactory(javax.swing.JFormattedTextField.AbstractFormatterFactory newValue) {
        formattedTextFieldAdapter.setFormatterFactory(newValue);
    }

    public javax.swing.JFormattedTextField.AbstractFormatterFactory getFormatterFactory() {
        return formattedTextFieldAdapter.getFormatterFactory();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @java.lang.SuppressWarnings("unchecked")
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents

}