/* @(#)AbstractView.java

Copyright (c) 1996-2010 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.app;
import org.jhotdraw.api.app.View;
import java.util.prefs.*;
/**
 * This abstract class can be extended to implement a {@link View}.
 */
public abstract class AbstractView extends javax.swing.JPanel implements org.jhotdraw.api.app.View {
    private static final long serialVersionUID = 1L;

    private org.jhotdraw.api.app.Application application;

    /**
     * The executor used to perform background tasks for the View in a controlled manner. This
     * executor ensures that all background tasks are executed sequentually.
     */
    protected java.util.concurrent.ExecutorService executor;

    /**
     * This is set to true, if the view has unsaved changes.
     */
    private boolean hasUnsavedChanges;

    /**
     * The preferences of the view.
     */
    protected java.util.prefs.Preferences preferences;

    /**
     * This id is used to make multiple open views of the same URI identifiable.
     */
    private int multipleOpenId = 1;

    /**
     * This is set to true, if the view is showing.
     */
    private boolean isShowing;

    /**
     * The title of the view.
     */
    private java.lang.String title;

    /**
     * List of objects that need to be disposed when this view is disposed.
     */
    private java.util.LinkedList<org.jhotdraw.api.app.Disposable> disposables;

    /**
     * The URI of the view. Has a null value, if the view has not been loaded from a URI or has not
     * been saved yet.
     */
    protected java.net.URI uri;

    public AbstractView() {
        preferences = org.jhotdraw.util.prefs.PreferencesUtil.userNodeForPackage(getClass());
    }

    /**
     * Initializes the view. This method does nothing, subclasses don't neet to call super.
     */
    @java.lang.Override
    public void init() {
    }

    /**
     * Starts the view. This method does nothing, subclasses don't neet to call super.
     */
    @java.lang.Override
    public void start() {
    }

    /**
     * Activates the view. This method does nothing, subclasses don't neet to call super.
     */
    @java.lang.Override
    public void activate() {
    }

    /**
     * Deactivates the view. This method does nothing, subclasses don't neet to call super.
     */
    @java.lang.Override
    public void deactivate() {
    }

    /**
     * Stops the view. This method does nothing, subclasses don't neet to call super.
     */
    @java.lang.Override
    public void stop() {
    }

    /**
     * Gets rid of all the resources of the view. No other methods should be invoked on the view
     * afterwards.
     */
    @java.lang.SuppressWarnings("unchecked")
    @java.lang.Override
    public void dispose() {
        if (executor != null) {
            executor.shutdown();
            executor = null;
        }
        if (disposables != null) {
            for (org.jhotdraw.api.app.Disposable d : ((java.util.LinkedList<org.jhotdraw.api.app.Disposable>) (disposables.clone()))) {
                d.dispose();
            }
            disposables = null;
        }
        removeAll();
    }

    @java.lang.Override
    public boolean canSaveTo(java.net.URI uri) {
        return true;
    }

    @java.lang.Override
    public java.net.URI getURI() {
        return uri;
    }

    @java.lang.Override
    public void setURI(java.net.URI newValue) {
        java.net.URI oldValue = uri;
        uri = newValue;
        if ((preferences != null) && (newValue != null)) {
            preferences.put("projectFile", newValue.toString());
        }
        firePropertyChange(org.jhotdraw.api.app.View.URI_PROPERTY, oldValue, newValue);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @java.lang.Override
    public void setApplication(org.jhotdraw.api.app.Application newValue) {
        org.jhotdraw.api.app.Application oldValue = application;
        application = newValue;
        firePropertyChange("application", oldValue, newValue);
    }

    @java.lang.Override
    public org.jhotdraw.api.app.Application getApplication() {
        return application;
    }

    @java.lang.Override
    public javax.swing.JComponent getComponent() {
        return this;
    }

    @java.lang.Override
    public boolean isEmpty() {
        return (getURI() == null) && (!hasUnsavedChanges());
    }

    /**
     * Returns true, if the view has unsaved changes. This is a bound property.
     */
    @java.lang.Override
    public boolean hasUnsavedChanges() {
        return hasUnsavedChanges;
    }

    protected void setHasUnsavedChanges(boolean newValue) {
        boolean oldValue = hasUnsavedChanges;
        hasUnsavedChanges = newValue;
        firePropertyChange(org.jhotdraw.api.app.View.HAS_UNSAVED_CHANGES_PROPERTY, oldValue, newValue);
    }

    /**
     * Executes the specified runnable on the worker thread of the view. Execution is performed
     * sequentially in the same sequence as the runnables have been passed to this method.
     */
    @java.lang.Override
    public void execute(java.lang.Runnable worker) {
        if (executor == null) {
            executor = java.util.concurrent.Executors.newSingleThreadExecutor();
        }
        executor.execute(worker);
    }

    @java.lang.Override
    public void setMultipleOpenId(int newValue) {
        int oldValue = multipleOpenId;
        multipleOpenId = newValue;
        firePropertyChange(org.jhotdraw.api.app.View.MULTIPLE_OPEN_ID_PROPERTY, oldValue, newValue);
    }

    @java.lang.Override
    public int getMultipleOpenId() {
        return multipleOpenId;
    }

    @java.lang.Override
    public void setShowing(boolean newValue) {
        boolean oldValue = isShowing;
        isShowing = newValue;
        firePropertyChange(org.jhotdraw.api.app.View.SHOWING_PROPERTY, oldValue, newValue);
    }

    @java.lang.Override
    public boolean isShowing() {
        return isShowing;
    }

    @java.lang.Override
    public void markChangesAsSaved() {
        setHasUnsavedChanges(false);
    }

    @java.lang.Override
    public void setTitle(java.lang.String newValue) {
        java.lang.String oldValue = title;
        title = newValue;
        firePropertyChange(org.jhotdraw.api.app.View.TITLE_PROPERTY, oldValue, newValue);
    }

    @java.lang.Override
    public java.lang.String getTitle() {
        return title;
    }

    /**
     * Adds a disposable object, which will be disposed when the specified view is disposed.
     *
     * @param disposable
     */
    @java.lang.Override
    public void addDisposable(org.jhotdraw.api.app.Disposable disposable) {
        if (disposables == null) {
            disposables = new java.util.LinkedList<>();
        }
        disposables.add(disposable);
    }

    /**
     * Removes a disposable object, which was previously added.
     *
     * @param disposable
     */
    @java.lang.Override
    public void removeDisposable(org.jhotdraw.api.app.Disposable disposable) {
        if (disposables != null) {
            disposables.remove(disposable);
            if (disposables.isEmpty()) {
                disposables = null;
            }
        }
    }
}