/* @(#)ActivityManagerEvent.java

Copyright (c) 2011 The authors and contributors of JHotDraw.

You may not use, copy or modify this file, except in compliance with the
license agreement you entered into with the copyright holders. For details
see accompanying license terms.
 */
package org.jhotdraw.gui.event;
/**
 * An event generated by the {@link org.jhotdraw.gui.ActivityManager}.
 *
 * @author Werner Randelshofer
 * @version 1.0 2011-09-08 Created.
 */
public class ActivityManagerEvent extends java.util.EventObject {
    private static final long serialVersionUID = 1L;

    private org.jhotdraw.api.gui.ActivityModel activity;

    public ActivityManagerEvent(java.lang.Object source, org.jhotdraw.api.gui.ActivityModel activity) {
        super(source);
        this.activity = activity;
    }

    public org.jhotdraw.api.gui.ActivityModel getActivityModel() {
        return activity;
    }
}