/**
 *
 * @(#)PaletteFontChooserPreviewPanel.java <p>Copyright (c) 1996-2010 The authors and contributors of JHotDraw. You may not use, copy or
modify this file, except in compliance with the accompanying license terms.
 */
package org.jhotdraw.gui.plaf.palette;
/**
 * PaletteFontChooserPreviewPanel.
 */
// End of variables declaration//GEN-END:variables
public class PaletteFontChooserPreviewPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form PaletteFontChooserPreviewPanel
     */
    public PaletteFontChooserPreviewPanel() {
        initComponents();
        previewLabel.setUI(((javax.swing.plaf.LabelUI) (org.jhotdraw.gui.plaf.palette.PaletteLabelUI.createUI(previewLabel))));
        previewLabel.setBackground(java.awt.Color.WHITE);
        previewLabel.setForeground(java.awt.Color.BLACK);
        previewLabel.setOpaque(true);
        setPreferredSize(new java.awt.Dimension(100, 50));
        setMinimumSize(new java.awt.Dimension(100, 50));
    }

    public void setSelectedFont(java.awt.Font newValue) {
        if (newValue == null) {
            previewLabel.setText(((java.lang.String) (org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel.getInstance().get("FontChooser.nothingSelected"))));
            previewLabel.setFont(getFont());
        } else {
            previewLabel.setText(beautifyName(newValue.getFontName()));
            previewLabel.setFont(newValue.deriveFont(24.0F));
        }
    }

    private java.lang.String beautifyName(java.lang.String name) {
        // 'Beautify' the name
        java.lang.StringBuilder buf = new java.lang.StringBuilder();
        char prev = name.charAt(0);
        buf.append(prev);
        for (int i = 1; i < name.length(); i++) {
            char ch = name.charAt(i);
            if (((((prev != ' ') && (prev != '-')) && java.lang.Character.isUpperCase(ch)) && (!java.lang.Character.isUpperCase(prev))) || (java.lang.Character.isDigit(ch) && (!java.lang.Character.isDigit(prev)))) {
                buf.append(' ');
            }
            buf.append(ch);
            prev = ch;
        }
        name = buf.toString();
        return name;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @java.lang.SuppressWarnings("unchecked")
    private void initComponents() {
        previewLabel = new javax.swing.JLabel();
        setLayout(new java.awt.BorderLayout());
        previewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(previewLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel previewLabel;
}