/* @(#)ArrangeToolBar.java

Copyright (c) 2008 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.samples.svg.gui;
/**
 * ArrangeToolBar.
 */
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
public class ArrangeToolBar extends org.jhotdraw.samples.svg.gui.AbstractToolBar {
    private static final long serialVersionUID = 1L;

    private org.jhotdraw.draw.event.SelectionComponentDisplayer displayer;

    /**
     * Creates new instance.
     */
    public ArrangeToolBar() {
        org.jhotdraw.util.ResourceBundleUtil labels = org.jhotdraw.util.ResourceBundleUtil.getBundle("org.jhotdraw.samples.svg.Labels");
        setName(labels.getString(getID() + ".toolbar"));
    }

    @java.lang.Override
    public void setEditor(org.jhotdraw.draw.DrawingEditor newValue) {
        if (displayer != null) {
            displayer.dispose();
            displayer = null;
        }
        super.setEditor(newValue);
        if (newValue != null) {
            displayer = new org.jhotdraw.draw.event.SelectionComponentDisplayer(editor, this);
            displayer.setVisibleIfCreationTool(false);
        }
    }

    @java.lang.Override
    protected javax.swing.JComponent createDisclosedComponent(int state) {
        javax.swing.JPanel p = null;
        switch (state) {
            case 1 :
                p = new javax.swing.JPanel();
                p.setOpaque(false);
                p.setBorder(new javax.swing.border.EmptyBorder(5, 5, 5, 8));
                // Abort if no editor is set
                if (editor == null) {
                    break;
                }
                org.jhotdraw.util.ResourceBundleUtil labels = org.jhotdraw.util.ResourceBundleUtil.getBundle("org.jhotdraw.samples.svg.Labels");
                java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
                p.setLayout(layout);
                java.awt.GridBagConstraints gbc;
                javax.swing.AbstractButton btn;
                org.jhotdraw.draw.action.AbstractSelectedAction d;
                btn = new javax.swing.JButton(d = new org.jhotdraw.draw.action.BringToFrontAction(editor));
                disposables.add(d);
                btn.setUI(((org.jhotdraw.gui.plaf.palette.PaletteButtonUI) (org.jhotdraw.gui.plaf.palette.PaletteButtonUI.createUI(btn))));
                btn.setText(null);
                labels.configureToolBarButton(btn, org.jhotdraw.draw.action.BringToFrontAction.ID);
                btn.putClientProperty("hideActionText", java.lang.Boolean.TRUE);
                gbc = new java.awt.GridBagConstraints();
                gbc.gridy = 0;
                gbc.anchor = java.awt.GridBagConstraints.EAST;
                p.add(btn, gbc);
                btn = new javax.swing.JButton(d = new org.jhotdraw.draw.action.SendToBackAction(editor));
                disposables.add(d);
                btn.setUI(((org.jhotdraw.gui.plaf.palette.PaletteButtonUI) (org.jhotdraw.gui.plaf.palette.PaletteButtonUI.createUI(btn))));
                btn.setText(null);
                labels.configureToolBarButton(btn, org.jhotdraw.draw.action.SendToBackAction.ID);
                btn.putClientProperty("hideActionText", java.lang.Boolean.TRUE);
                btn.setUI(((org.jhotdraw.gui.plaf.palette.PaletteButtonUI) (org.jhotdraw.gui.plaf.palette.PaletteButtonUI.createUI(btn))));
                gbc = new java.awt.GridBagConstraints();
                gbc.gridy = 1;
                gbc.insets = new java.awt.Insets(3, 0, 0, 0);
                gbc.anchor = java.awt.GridBagConstraints.NORTH;
                gbc.weighty = 1.0F;
                p.add(btn, gbc);
                break;
        }
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setOpaque(false);
    }// </editor-fold>//GEN-END:initComponents


    @java.lang.Override
    protected java.lang.String getID() {
        return "arrange";
    }
}