/* @(#)SummaryToolBar.java

Copyright (c) 2007-2008 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.samples.svg.gui;
/**
 * SummaryToolBar.
 */
// End of variables declaration//GEN-END:variables
public class SummaryToolBar extends javax.swing.JToolBar {
    private static final long serialVersionUID = 1L;

    private org.jhotdraw.util.ResourceBundleUtil labels;

    /**
     * Creates new instance.
     */
    public SummaryToolBar() {
        labels = org.jhotdraw.util.ResourceBundleUtil.getBundle("org.jhotdraw.samples.svg.Labels");
        initComponents();
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        setLayout(layout);
        java.awt.GridBagConstraints gbc;
        gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(0, 10, 0, 0);
        gbc.weightx = 1.0;
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        layout.setConstraints(summaryField, gbc);
    }

    public java.lang.String getSummary() {
        return summaryField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        summaryLabel = new javax.swing.JLabel();
        summaryField = new javax.swing.JTextField();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setFloatable(false);
        setOpaque(false);
        summaryLabel.setFont(new java.awt.Font("Dialog", 0, 11));
        summaryLabel.setText(labels.getString("summary"));// NOI18N

        add(summaryLabel);
        summaryField.setFont(new java.awt.Font("DialogInput", 0, 11));
        add(summaryField);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField summaryField;

    private javax.swing.JLabel summaryLabel;
}