/* @(#)PaletteColorSlidersChooser.java

Copyright (c) 1996-2010 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.gui.plaf.palette.colorchooser;
/**
 * The ColorSlidersChooser contains four individual color slider pages: gray slider, RGB sliders,
 * CMYK sliders, and HTML sliders.
 */
// End of variables declaration//GEN-END:variables
public class PaletteColorSlidersChooser extends javax.swing.colorchooser.AbstractColorChooserPanel implements javax.swing.plaf.UIResource {
    private static final long serialVersionUID = 1L;

    /**
     * We store here the name of the last selected color sliders panel. When the ColorSlidersChooser
     * is recreated multiple times in the same panel, the application 'remembers' which panel the user
     * had opened before.
     */
    private static int lastSelectedPanelIndex = 0;

    /**
     * Creates new form.
     */
    public PaletteColorSlidersChooser() {
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        slidersComboBox = new javax.swing.JComboBox();
        slidersHolder = new javax.swing.JPanel();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 6, 6, 6));
        setLayout(new java.awt.BorderLayout());
        add(slidersComboBox, java.awt.BorderLayout.NORTH);
        slidersHolder.setLayout(new java.awt.CardLayout());
        add(slidersHolder, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    @java.lang.Override
    protected void buildChooser() {
        initComponents();
        org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel laf = org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel.getInstance();
        setUI(org.jhotdraw.gui.plaf.palette.PalettePanelUI.createUI(this));
        slidersHolder.setUI(((javax.swing.plaf.PanelUI) (org.jhotdraw.gui.plaf.palette.PalettePanelUI.createUI(slidersHolder))));
        slidersComboBox.setFont(laf.getFont("ColorChooser.font"));
        slidersHolder.add(new org.jhotdraw.gui.plaf.palette.colorchooser.PaletteRGBChooser(), "" + laf.getString("ColorChooser.rgbSliders"));
        slidersHolder.add(new org.jhotdraw.gui.plaf.palette.colorchooser.PaletteCMYKChooser(), "" + laf.getString("ColorChooser.cmykSliders"));
        slidersHolder.add(new org.jhotdraw.gui.plaf.palette.colorchooser.PaletteHSBChooser(), "" + laf.getString("ColorChooser.hsbSliders"));
        javax.swing.DefaultComboBoxModel cbm = new javax.swing.DefaultComboBoxModel();
        cbm.addElement(laf.getString("ColorChooser.rgbSliders"));
        cbm.addElement(laf.getString("ColorChooser.cmykSliders"));
        cbm.addElement(laf.getString("ColorChooser.hsbSliders"));
        slidersComboBox.setModel(cbm);
        slidersComboBox.addItemListener(new java.awt.event.ItemListener() {
            @java.lang.Override
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    ((java.awt.CardLayout) (slidersHolder.getLayout())).show(slidersHolder, ((java.lang.String) (evt.getItem())));
                    org.jhotdraw.gui.plaf.palette.colorchooser.PaletteColorSlidersChooser.lastSelectedPanelIndex = slidersComboBox.getSelectedIndex();
                }
            }
        });
        slidersComboBox.setSelectedIndex(org.jhotdraw.gui.plaf.palette.colorchooser.PaletteColorSlidersChooser.lastSelectedPanelIndex);
    }

    @java.lang.Override
    public void installChooserPanel(javax.swing.JColorChooser enclosingChooser) {
        super.installChooserPanel(enclosingChooser);
        java.awt.Component[] components = slidersHolder.getComponents();
        for (java.awt.Component component : components) {
            javax.swing.colorchooser.AbstractColorChooserPanel ccp = ((javax.swing.colorchooser.AbstractColorChooserPanel) (component));
            ccp.installChooserPanel(enclosingChooser);
        }
    }

    /**
     * Invoked when the panel is removed from the chooser. If override this, be sure to call <code>
     * super</code>.
     */
    @java.lang.Override
    public void uninstallChooserPanel(javax.swing.JColorChooser enclosingChooser) {
        java.awt.Component[] components = slidersHolder.getComponents();
        for (java.awt.Component component : components) {
            javax.swing.colorchooser.AbstractColorChooserPanel ccp = ((javax.swing.colorchooser.AbstractColorChooserPanel) (component));
            ccp.uninstallChooserPanel(enclosingChooser);
        }
        super.uninstallChooserPanel(enclosingChooser);
    }

    @java.lang.Override
    public java.lang.String getDisplayName() {
        org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel laf = org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel.getInstance();
        return laf.getString("ColorChooser.colorSliders");
    }

    @java.lang.Override
    public javax.swing.Icon getLargeDisplayIcon() {
        org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel laf = org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel.getInstance();
        return laf.getIcon("ColorChooser.colorSlidersIcon");
    }

    @java.lang.Override
    public javax.swing.Icon getSmallDisplayIcon() {
        return getLargeDisplayIcon();
    }

    @java.lang.Override
    public void updateChooser() {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox slidersComboBox;

    private javax.swing.JPanel slidersHolder;
}