/* @(#)PaletteColorChooserPreviewPanel.java

Copyright (c) 1996-2010 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.gui.plaf.palette.colorchooser;
/**
 * PaletteColorChooserPreviewPanel.
 */
// Variables declaration - do not modify//GEN-BEGIN:variables
// End of variables declaration//GEN-END:variables
public class PaletteColorChooserPreviewPanel extends javax.swing.JPanel implements javax.swing.plaf.UIResource {
    private static final long serialVersionUID = 1L;

    private static final java.awt.Color PREVIEW_BORDER_COLOR = new java.awt.Color(0x949494);

    private static final java.awt.Color PREVIEW_BACKGROUND_COLOR = new java.awt.Color(0xffffff);

    /**
     * Creates new form.
     */
    public PaletteColorChooserPreviewPanel() {
        initComponents();
        // setBorder(new VisualMargin(3,0,3,0));
        setToolTipText("on");// set dummy text, to switch tooltip on

    }

    @java.lang.Override
    public void paintComponent(java.awt.Graphics g) {
        java.awt.Insets insets = getInsets();
        int x = insets.left;
        int y = insets.top;
        int w = (getWidth() - insets.left) - insets.right;
        int h = (getHeight() - insets.top) - insets.bottom;
        g.setColor(org.jhotdraw.gui.plaf.palette.colorchooser.PaletteColorChooserPreviewPanel.PREVIEW_BACKGROUND_COLOR);
        g.fillRect(x + 1, y + 1, w - 2, h - 2);
        g.setColor(org.jhotdraw.gui.plaf.palette.colorchooser.PaletteColorChooserPreviewPanel.PREVIEW_BORDER_COLOR);
        g.drawRect(x, y, w - 1, h - 1);
        g.setColor(getForeground());
        g.fillRect(x + 2, y + 2, w - 4, h - 4);
    }

    @java.lang.Override
    public java.lang.String getToolTipText(java.awt.event.MouseEvent evt) {
        java.awt.Color color = getForeground();
        return color == null ? null : (((color.getRed() + ", ") + color.getGreen()) + ", ") + color.getBlue();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setPreferredSize(new java.awt.Dimension(26, 26));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

}