/* @(#)PaletteSwatchesChooser.java

Copyright (c) 2010 The authors and contributors of JHotDraw.

You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.gui.plaf.palette.colorchooser;
/**
 * PaletteSwatchesChooser.
 */
public class PaletteSwatchesChooser extends javax.swing.colorchooser.AbstractColorChooserPanel {
    private static final long serialVersionUID = 1L;

    private int updateRecursion = 0;

    /**
     * HSB color palette with a set of colors chosen based on a physical criteria.
     *
     * <p>This is a 'human friendly' color palette which arranges the color in a way that makes it
     * easy for humans to select the desired color. The colors are ordered in a way which minimizes
     * the color contrast effect in the human visual system.
     *
     * <p>This palette has 12 columns and 10 rows.
     *
     * <p>The topmost row contains a null-color and a gray scale from white to black in 10 percent
     * steps.
     *
     * <p>The remaining rows contain colors taken from the outer hull of the HSB color model:
     *
     * <p>The columns are ordered by hue starting with red - the lowest wavelength - and ending with
     * purple - the highest wavelength. There are 12 different hues, so that all primary colors with
     * their additive complements can be selected.
     *
     * <p>The rows are orderd by brightness with the brightest color at the top (sky) and the darkest
     * color at the bottom (earth). The first 5 rows contain colors with maximal brightness and a
     * saturation ranging form 20% up to 100%. The remaining 4 rows contain colors with maximal
     * saturation and a brightness ranging from 90% to 20% (this also makes for a range from 100% to
     * 20% if the 5th row is taken into account).
     */
    private static final java.util.List<org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon> HSB_COLORS;

    private static final int HSB_COLORS_COLUMN_COUNT = 12;

    /**
     * This is the same palette as HSB_COLORS, but all color values are specified in the sRGB color
     * space.
     */
    private static final java.util.List<org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon> HSB_COLORS_AS_RGB;

    private static final int HSB_COLORS_AS_RGB_COLUMN_COUNT = 12;

    static {
        // FIXME - Move this into a lazy initializer
        org.jhotdraw.color.HSBColorSpace hsbCS = org.jhotdraw.color.HSBColorSpace.getInstance();
        java.util.List<org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon> m = new java.util.ArrayList<>();
        org.jhotdraw.util.ResourceBundleUtil labels = org.jhotdraw.util.ResourceBundleUtil.getBundle("org.jhotdraw.gui.Labels");
        for (int s = 2; s <= 8; s += 2) {
            for (int h = 0; h < 12; h++) {
                java.awt.Color c = new java.awt.Color(hsbCS, new float[]{ h / 12.0F, s * 0.1F, 1.0F }, 1.0F);
                m.add(new org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon(c, labels.getFormatted("ColorChooser.colorSwatch.hsbComponents.toolTipText", (h * 360) / 12, s * 10, 100)));
            }
        }
        for (int b = 10; b >= 2; b -= 2) {
            for (int h = 0; h < 12; h++) {
                java.awt.Color c = new java.awt.Color(hsbCS, new float[]{ h / 12.0F, 1.0F, b * 0.1F }, 1.0F);
                m.add(new org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon(new java.awt.Color(hsbCS, new float[]{ h / 12.0F, 1.0F, b * 0.1F }, 1.0F), labels.getFormatted("ColorChooser.colorSwatch.hsbComponents.toolTipText", (h * 360) / 12, 100, b * 10)));
            }
        }
        m.add(new org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon(new java.awt.Color(0, true), labels.getToolTipTextProperty("ColorChooser.colorSwatch.noColor")));
        HSB_COLORS = java.util.Collections.unmodifiableList(m);
        m = new java.util.ArrayList<>();
        for (org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon ci : HSB_COLORS) {
            if (ci.getColor() == null) {
                m.add(new org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon(new java.awt.Color(0, true), labels.getToolTipTextProperty("ColorChooser.colorSwatch.noColor")));
            } else {
                java.awt.Color c = ci.getColor();
                m.add(new org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon(c, labels.getFormatted("ColorChooser.colorSwatch.rgbComponents.toolTipText", c.getRed(), c.getGreen(), c.getBlue())));
            }
        }
        HSB_COLORS_AS_RGB = java.util.Collections.unmodifiableList(m);
    }

    /**
     * Creates new form PaletteSwatchesChooser
     */
    public PaletteSwatchesChooser() {
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @java.lang.SuppressWarnings("unchecked")
    private void initComponents() {
        jList = new javax.swing.JList();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 6, 6, 6));
        setLayout(new java.awt.GridBagLayout());
        jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        add(jList, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList;

    // End of variables declaration//GEN-END:variables
    @java.lang.Override
    public void updateChooser() {
        if ((updateRecursion++) == 0) {
            javax.swing.ListModel m = jList.getModel();
            java.awt.Color mc = getColorFromModel();
            if (mc != null) {
                int ma = mc.getAlpha();
                int mr = mc.getRed();
                int mg = mc.getGreen();
                int mb = mc.getBlue();
                int closestSquaredDistance = java.lang.Integer.MAX_VALUE;
                int closestIndex = -1;
                for (int i = 0, n = m.getSize(); i < n; i++) {
                    org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon item = ((org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon) (m.getElementAt(i)));
                    java.awt.Color ic = (item == null) ? null : item.getColor();
                    int squaredDistance;
                    if ((ic == null) || (ic.getAlpha() != ma)) {
                        squaredDistance = java.lang.Integer.MAX_VALUE;
                    } else {
                        squaredDistance = (((mr - ic.getRed()) * (mr - ic.getRed())) + ((mg - ic.getGreen()) * (mg - ic.getGreen()))) + ((mb - ic.getBlue()) * (mb - ic.getBlue()));
                    }
                    if (squaredDistance <= closestSquaredDistance) {
                        closestSquaredDistance = squaredDistance;
                        closestIndex = i;
                        if (squaredDistance == 0) {
                            break;
                        }
                    }
                }
                if (closestIndex == (-1)) {
                    jList.clearSelection();
                } else {
                    jList.setSelectedIndex(closestIndex);
                }
            }
        }
        updateRecursion--;
    }

    @java.lang.Override
    public java.lang.String getDisplayName() {
        return org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel.getInstance().getString("ColorChooser.colorSwatches");
    }

    @java.lang.Override
    public javax.swing.Icon getSmallDisplayIcon() {
        return org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel.getInstance().getIcon("ColorChooser.colorSwatchesIcon");
    }

    @java.lang.Override
    public javax.swing.Icon getLargeDisplayIcon() {
        return getSmallDisplayIcon();
    }

    @java.lang.Override
    protected void buildChooser() {
        initComponents();
        setUI(org.jhotdraw.gui.plaf.palette.PalettePanelUI.createUI(this));
        jList.setUI(((javax.swing.plaf.ListUI) (org.jhotdraw.gui.plaf.palette.PaletteListUI.createUI(jList))));
        java.lang.Object[] byRows = org.jhotdraw.gui.plaf.palette.colorchooser.PaletteSwatchesChooser.HSB_COLORS_AS_RGB.toArray();
        java.lang.Object[] byColumns = new java.lang.Object[byRows.length];
        for (int y = 0, my = byRows.length / org.jhotdraw.gui.plaf.palette.colorchooser.PaletteSwatchesChooser.HSB_COLORS_AS_RGB_COLUMN_COUNT; y < my; y++) {
            for (int x = 0; x < org.jhotdraw.gui.plaf.palette.colorchooser.PaletteSwatchesChooser.HSB_COLORS_AS_RGB_COLUMN_COUNT; x++) {
                if (((x * my) + y) < byColumns.length) {
                    byColumns[(x * my) + y] = byRows[(y * org.jhotdraw.gui.plaf.palette.colorchooser.PaletteSwatchesChooser.HSB_COLORS_AS_RGB_COLUMN_COUNT) + x];
                }
            }
        }
        byColumns[byColumns.length - 1] = byRows[byRows.length - 1];
        jList.setListData(byColumns);
        jList.setVisibleRowCount(org.jhotdraw.gui.plaf.palette.colorchooser.PaletteSwatchesChooser.HSB_COLORS_AS_RGB.size() / org.jhotdraw.gui.plaf.palette.colorchooser.PaletteSwatchesChooser.HSB_COLORS_AS_RGB_COLUMN_COUNT);
        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @java.lang.Override
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                if ((updateRecursion++) == 0) {
                    org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon item = ((org.jhotdraw.gui.plaf.palette.colorchooser.ColorIcon) (jList.getSelectedValue()));
                    setColorToModel(item == null ? null : item.getColor());
                }
                updateRecursion--;
            }
        });
    }

    public void setColorToModel(java.awt.Color color) {
        getColorSelectionModel().setSelectedColor(color);
    }
}