/* @(#)PaletteColorWheelChooser.java

Copyright (c) 1996-2010 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.gui.plaf.palette.colorchooser;
/**
 * A HSB color chooser, which displays a hue/saturation color wheel, and a brightness slider.
 */
// End of variables declaration//GEN-END:variables
public class PaletteColorWheelChooser extends javax.swing.colorchooser.AbstractColorChooserPanel implements javax.swing.plaf.UIResource {
    private static final long serialVersionUID = 1L;

    private org.jhotdraw.color.JColorWheel colorWheel;

    private org.jhotdraw.gui.plaf.palette.colorchooser.PaletteColorSliderModel ccModel = new org.jhotdraw.gui.plaf.palette.colorchooser.PaletteColorSliderModel(new org.jhotdraw.color.HSVColorSpace());

    private int updatingChooser;

    public PaletteColorWheelChooser() {
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        brightnessSlider = new javax.swing.JSlider();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 6, 6, 6));
        setLayout(new java.awt.BorderLayout());
        brightnessSlider.setMajorTickSpacing(50);
        brightnessSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        brightnessSlider.setPaintTicks(true);
        add(brightnessSlider, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    @java.lang.Override
    protected void buildChooser() {
        initComponents();
        setUI(org.jhotdraw.gui.plaf.palette.PalettePanelUI.createUI(this));
        int textSliderGap = org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel.getInstance().getInt("ColorChooser.textSliderGap");
        if (textSliderGap != 0) {
            java.awt.BorderLayout layout = ((java.awt.BorderLayout) (getLayout()));
            layout.setHgap(textSliderGap);
        }
        colorWheel = new org.jhotdraw.color.JColorWheel();
        add(colorWheel);
        ccModel.configureSlider(2, brightnessSlider);
        brightnessSlider.setMaximum(200);
        colorWheel.setModel(ccModel);
        ccModel.addChangeListener(new javax.swing.event.ChangeListener() {
            @java.lang.Override
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                setColorToModel(ccModel.getColor());
            }
        });
    }

    @java.lang.Override
    public java.lang.String getDisplayName() {
        return org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel.getInstance().getString("ColorChooser.colorWheel");
    }

    @java.lang.Override
    public javax.swing.Icon getLargeDisplayIcon() {
        return org.jhotdraw.gui.plaf.palette.PaletteLookAndFeel.getInstance().getIcon("ColorChooser.colorWheelIcon");
    }

    @java.lang.Override
    public javax.swing.Icon getSmallDisplayIcon() {
        return getLargeDisplayIcon();
    }

    @java.lang.Override
    public void updateChooser() {
        updatingChooser++;
        ccModel.setColor(getColorFromModel());
        updatingChooser--;
    }

    public void setColorToModel(java.awt.Color color) {
        if (updatingChooser == 0) {
            getColorSelectionModel().setSelectedColor(color);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider brightnessSlider;
}