/* @(#)ColorWheelChooser.java

Copyright (c) 2008 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.color;
import javax.swing.colorchooser.*;
/**
 * A HSB color chooser, which displays a hue/saturation color wheel, and a brightness slider.
 */
// End of variables declaration//GEN-END:variables
public class ColorWheelChooser extends javax.swing.colorchooser.AbstractColorChooserPanel implements javax.swing.plaf.UIResource {
    private static final long serialVersionUID = 1L;

    private org.jhotdraw.color.JColorWheel colorWheel;

    private org.jhotdraw.color.ColorSliderModel ccModel = new org.jhotdraw.color.DefaultColorSliderModel(org.jhotdraw.color.HSBColorSpace.getInstance());

    private int updatingChooser;

    public ColorWheelChooser() {
        initComponents();
        int textSliderGap = javax.swing.UIManager.getInt("ColorChooser.textSliderGap");
        if (textSliderGap != 0) {
            java.awt.BorderLayout layout = ((java.awt.BorderLayout) (getLayout()));
            layout.setHgap(textSliderGap);
        }
        colorWheel = new org.jhotdraw.color.JColorWheel();
        add(colorWheel);
        ccModel.configureSlider(2, brightnessSlider);
        colorWheel.setModel(ccModel);
        ccModel.addChangeListener(new javax.swing.event.ChangeListener() {
            @java.lang.Override
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                setColorToModel(ccModel.getColor());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    private void initComponents() {
        // GEN-BEGIN:initComponents
        brightnessSlider = new javax.swing.JSlider();
        setLayout(new java.awt.BorderLayout());
        brightnessSlider.setMajorTickSpacing(50);
        brightnessSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        brightnessSlider.setPaintTicks(true);
        add(brightnessSlider, java.awt.BorderLayout.EAST);
    }// GEN-END:initComponents


    @java.lang.Override
    protected void buildChooser() {
    }

    @java.lang.Override
    public java.lang.String getDisplayName() {
        return javax.swing.UIManager.getString("ColorChooser.colorWheel");
    }

    @java.lang.Override
    public javax.swing.Icon getLargeDisplayIcon() {
        return javax.swing.UIManager.getIcon("ColorChooser.colorWheelIcon");
    }

    @java.lang.Override
    public javax.swing.Icon getSmallDisplayIcon() {
        return getLargeDisplayIcon();
    }

    @java.lang.Override
    public void updateChooser() {
        updatingChooser++;
        ccModel.setColor(getColorFromModel());
        updatingChooser--;
    }

    public void setColorToModel(java.awt.Color color) {
        if (updatingChooser == 0) {
            getColorSelectionModel().setSelectedColor(color);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider brightnessSlider;
}