/* @(#)CharacterSetAccessory.java

Copyright (c) 2005 The authors and contributors of JHotDraw.
You may not use, copy or modify this file, except in compliance with the
accompanying license terms.
 */
package org.jhotdraw.samples.teddy;
/**
 * CharacterSetAccessory.
 */
// End of variables declaration//GEN-END:variables
public class CharacterSetAccessory extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    private static final java.util.prefs.Preferences PREFS = org.jhotdraw.util.prefs.PreferencesUtil.userNodeForPackage(org.jhotdraw.samples.teddy.TeddyView.class);

    private static java.lang.Object[] availableCharSets;

    public CharacterSetAccessory() {
        if ("aqua".equals(javax.swing.UIManager.getLookAndFeel().getID().toLowerCase())) {
            initComponents();
        } else {
            initComponentsWin();
        }
        java.lang.String selectedItem = org.jhotdraw.samples.teddy.CharacterSetAccessory.PREFS.get("characterSet", "UTF-8");
        charSetCombo.setModel(new javax.swing.DefaultComboBoxModel(new java.lang.String[]{ selectedItem }));
        charSetCombo.setSelectedItem(selectedItem);
        charSetCombo.setEnabled(false);
        fetchAvailableCharSets();
        java.lang.String lineSeparator = org.jhotdraw.samples.teddy.CharacterSetAccessory.PREFS.get("lineSeparator", "\n");
        if ("\r".equals(lineSeparator)) {
            lineSepCombo.setSelectedIndex(0);
        } else if ("\n".equals(lineSeparator)) {
            lineSepCombo.setSelectedIndex(1);
        } else if ("\r\n".equals(lineSeparator)) {
            lineSepCombo.setSelectedIndex(2);
        }
    }

    public void fetchAvailableCharSets() {
        if (org.jhotdraw.samples.teddy.CharacterSetAccessory.availableCharSets == null) {
            new javax.swing.SwingWorker() {
                @java.lang.Override
                protected java.lang.Object doInBackground() throws java.lang.Exception {
                    java.util.SortedMap<java.lang.String, java.nio.charset.Charset> sm = java.nio.charset.Charset.availableCharsets();
                    java.util.LinkedList<java.lang.String> list = new java.util.LinkedList<java.lang.String>();
                    for (java.lang.String key : sm.keySet()) {
                        if (!key.startsWith("x-")) {
                            list.add(key);
                        }
                    }
                    org.jhotdraw.samples.teddy.CharacterSetAccessory.availableCharSets = list.toArray();
                    java.util.Arrays.sort(org.jhotdraw.samples.teddy.CharacterSetAccessory.availableCharSets);
                    return null;
                }

                @java.lang.Override
                public void done() {
                    java.lang.Object selectedItem = charSetCombo.getSelectedItem();
                    charSetCombo.setModel(new javax.swing.DefaultComboBoxModel(org.jhotdraw.samples.teddy.CharacterSetAccessory.availableCharSets));
                    charSetCombo.setSelectedItem(selectedItem);
                    charSetCombo.setEnabled(true);
                }
            }.execute();
        } else {
            java.lang.Object selectedItem = charSetCombo.getSelectedItem();
            charSetCombo.setModel(new javax.swing.DefaultComboBoxModel(org.jhotdraw.samples.teddy.CharacterSetAccessory.availableCharSets));
            charSetCombo.setSelectedItem(selectedItem);
            charSetCombo.setEnabled(true);
        }
    }

    public java.lang.String getCharacterSet() {
        org.jhotdraw.samples.teddy.CharacterSetAccessory.PREFS.put("characterSet", ((java.lang.String) (charSetCombo.getSelectedItem())));
        return ((java.lang.String) (charSetCombo.getSelectedItem()));
    }

    public java.lang.String getLineSeparator() {
        java.lang.String lineSeparator;
        switch (charSetCombo.getSelectedIndex()) {
            case 0 :
            default :
                lineSeparator = "\n";
                break;
            case 1 :
                lineSeparator = "\r";
                break;
            case 2 :
                lineSeparator = "\r\n";
                break;
        }
        org.jhotdraw.samples.teddy.CharacterSetAccessory.PREFS.put("lineSeparator", lineSeparator);
        return lineSeparator;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        charSetLabel = new javax.swing.JLabel();
        charSetCombo = new javax.swing.JComboBox();
        lineSepLabel = new javax.swing.JLabel();
        lineSepCombo = new javax.swing.JComboBox();
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        charSetLabel.setText("Character Set:");
        charSetCombo.setModel(new javax.swing.DefaultComboBoxModel(new java.lang.String[]{ "Item 1", "Item 2", "Item 3", "Item 4" }));
        lineSepLabel.setText("Line Separator:");
        lineSepCombo.setModel(new javax.swing.DefaultComboBoxModel(new java.lang.String[]{ "CR", "LF", "CR LF" }));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(charSetLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(charSetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(lineSepLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lineSepCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(charSetLabel).addComponent(charSetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lineSepLabel).addComponent(lineSepCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents


    private void initComponentsWin() {
        charSetLabel = new javax.swing.JLabel();
        charSetCombo = new javax.swing.JComboBox();
        lineSepLabel = new javax.swing.JLabel();
        lineSepCombo = new javax.swing.JComboBox();
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        charSetLabel.setText("Character Set:");
        charSetCombo.setModel(new javax.swing.DefaultComboBoxModel(new java.lang.String[]{ "Item 1", "Item 2", "Item 3", "Item 4" }));
        lineSepLabel.setText("Line Separator:");
        lineSepCombo.setModel(new javax.swing.DefaultComboBoxModel(new java.lang.String[]{ "CR", "LF", "CR LF" }));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(charSetLabel).addComponent(charSetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lineSepLabel).addComponent(lineSepCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(layout.createSequentialGroup().addComponent(charSetLabel).addComponent(charSetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(lineSepLabel).addComponent(lineSepCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox charSetCombo;

    public javax.swing.JLabel charSetLabel;

    public javax.swing.JComboBox lineSepCombo;

    public javax.swing.JLabel lineSepLabel;
}